// Brand names and images come from the portfolio folder supplied by the client.
// Only designs without identifiable customer faces are shown here.
export const portfolioCases = [
  {brand:'木門咖啡', kind:'品牌識別・菜單', image:'/portfolio/clients/wood-door.jpg', imageAlt:'木門咖啡品牌標誌設計', imagePosition:'center 8%'},
  {brand:'老井極上燒肉', kind:'網站設計', image:'/portfolio/clients/old-well.jpg', imageAlt:'老井極上燒肉網站設計', imagePosition:'center center'},
  {brand:'邁特電子', kind:'企業網站・廣告', image:'/portfolio/clients/mighty.jpg', imageAlt:'邁特電子宣傳設計', imagePosition:'center center'},
  {brand:'卡斯蒂拉', kind:'品牌包裝', image:'/portfolio/clients/castella.jpg', imageAlt:'卡斯蒂拉包裝設計', imagePosition:'center 67%'},
  {brand:'聯想電腦', kind:'廣告設計', image:'/portfolio/clients/lenovo.jpg', imageAlt:'聯想電腦宣傳設計', imagePosition:'center 15%'},
  {brand:'微熱山丘', kind:'活動視覺', image:'/portfolio/clients/sunnyhills.jpg', imageAlt:'微熱山丘宣傳設計', imagePosition:'center 30%'},
  {brand:'愛現眼鏡', kind:'活動視覺', image:'/portfolio/clients/eyewear.jpg', imageAlt:'愛現眼鏡活動設計', imagePosition:'center 18%'},
  {brand:'野椿拉麵', kind:'餐飲文宣', image:'/portfolio/clients/ramen.jpg', imageAlt:'野椿拉麵宣傳設計', imagePosition:'center 47%'},
  {brand:'美若康', kind:'禮盒包裝', image:'/portfolio/clients/miacare.jpg', imageAlt:'美若康禮盒包裝設計', imagePosition:'center 48%'},
  {brand:'喝嗎', kind:'品牌識別', image:'/portfolio/clients/hema.jpg', imageAlt:'喝嗎品牌識別設計', imagePosition:'center center'},
  {brand:'恰好食', kind:'菜單設計', image:'/portfolio/clients/qiahaoshi.jpg', imageAlt:'恰好食菜單設計', imagePosition:'center center'},
  {brand:'Mastro', kind:'餐飲文宣', image:'/portfolio/clients/mastro.jpg', imageAlt:'Mastro 餐飲文宣設計', imagePosition:'center center'},
  {brand:'伯倫正音', kind:'招生文宣', image:'/portfolio/clients/bolun.jpg', imageAlt:'伯倫正音宣傳設計', imagePosition:'center center'},
  {brand:'靴下羅森', kind:'品牌識別', image:'/portfolio/clients/socks.jpg', imageAlt:'靴下羅森品牌標誌設計', imagePosition:'center center'},
  {brand:'8村', kind:'品牌識別', image:'/portfolio/clients/eightvillage.jpg', imageAlt:'8村品牌標誌設計', imagePosition:'center center'},
  {brand:'明月鄉', kind:'網站設計', image:'/portfolio/clients/mingyue.jpg', imageAlt:'明月鄉網站設計', imagePosition:'center center'},
  {brand:'品心', kind:'網站設計', image:'/portfolio/clients/pinxin.jpg', imageAlt:'品心網站設計', imagePosition:'center center'},
  {brand:'thingsPKI', kind:'網站設計', image:'/portfolio/clients/thingspki.jpg', imageAlt:'thingsPKI 網站設計', imagePosition:'center center'},
  {brand:'山間小貓', kind:'品牌識別', image:'/portfolio/clients/cat.jpg', imageAlt:'山間小貓品牌標誌設計', imagePosition:'center center'},
  {brand:'103 Kitchen', kind:'品牌包裝', image:'/portfolio/clients/kitchen.jpg', imageAlt:'103 Kitchen 品牌包裝設計', imagePosition:'center center'},
  {brand:'紳裝主廚', kind:'品牌識別', image:'/portfolio/clients/chef.jpg', imageAlt:'紳裝主廚品牌標誌設計', imagePosition:'center center'},
  {brand:'旅行台灣', kind:'網站設計', image:'/portfolio/clients/travel.jpg', imageAlt:'旅行台灣網站設計', imagePosition:'center center'},
];
