"use client";
import {useState} from 'react';
import {ArrowUpRight,Check,ChevronDown,Clock3} from 'lucide-react';
import type {ServiceKey} from '@/lib/marketing';
const offers = [
 {key:'content' as ServiceKey,title:'五倍行銷月包',need:'我想穩定曝光、增加詢問',price:'35,000–50,000',unit:'／月',image:'sunny-team',alt:'老闆與團隊確認社群內容與影片',summary:'企劃＋圖文＋短影音，依工作量組合。',items:['每月 8 則圖文（每則文案＋1 張主圖）','每月 4 支 15–30 秒直式短影音','1 份內容月曆＋1 次 30 分鐘策略會議','FB／IG 同素材適配、核准後排程'],time:'素材齊備後，目標 5 個工作天交第一批。',revision:'每批 1 次集中修改；每月 2 批交付。',input:'品牌資料、產品照片／素材、當月主打商品。',extra:'不含廣告預算、現場拍攝、每日客服、網紅合作與額外平台；不承諾流量或成交。',payment:'建議按月預付，可先合作 1 個月。'},
 {key:'video' as ServiceKey,title:'AI 短影音包',need:'我有素材，想快速變成影片',price:'12,800',unit:'／4 支',image:'sunny-video',alt:'剪輯師以筆電製作產品短影音',summary:'一份素材，剪出四次曝光機會。',items:['4 支 15–30 秒、9:16 直式成片','開場文案、繁中字幕與基礎配樂','每支 1 張封面，統一品牌版型','使用客供素材，搭配必要的 AI 補充畫面'],time:'素材與腳本確認後，目標 5–7 個工作天。',revision:'每支 1 次集中修改，重寫腳本另估。',input:'總長 30 分鐘內的可用素材、產品資料與參考風格。',extra:'不含到場拍攝、真人演員、客製角色一致性、複雜 3D、額外比例與特殊授權。',payment:'建議啟動付 50%，成片驗收付 50%。'},
 {key:'operations' as ServiceKey,title:'AI 流程自動化',need:'我想少做表格、少追進度',price:'38,000',unit:'起／案',image:'sunny-operations',alt:'電商老闆查看訂單與管理報表',summary:'先讓最花時間的一件事自動完成。',items:['1 條明確流程，最多 2 個既有工具串接','最多 5 個約定處理步驟','例外提醒、執行紀錄與人工確認節點','1 次操作教學＋驗收後 14 天錯誤修正'],time:'資料與權限齊備後，目標 7–10 個工作天首版。',revision:'1 次流程確認＋1 次首版調整。',input:'現行流程、去識別化資料樣本、可串接帳號。',extra:'不含工具／API 訂閱、複雜資料清理、無 API 系統操作、新增流程及持續維運；先評估可行性。',payment:'建議啟動付 50%，依約驗收付 50%。'},
 {key:'software' as ServiceKey,title:'專案型軟體',need:'我需要一套本案專用的系統',price:'150,000',unit:'起／案',image:'desktop-software',alt:'桌上大型 iMac 展示管理系統概念介面',summary:'報名、報到、管理工具，為本案而做。',items:['1 個核心使用流程的網頁軟體首版','最多 5 個主要頁面、2 種使用角色','1 種約定格式的資料匯入／匯出','操作教學、部署與結案退場規劃'],time:'規格確認後，目標 15–20 個工作天首版。',revision:'原約定範圍內 2 次集中修改。',input:'必要功能、使用人數、資料範例、預算與截止日。',extra:'不含原生 App、金流、複雜 ERP 整合、主機／第三方費用及長期維護；資安與權限需求先納入估價。',payment:'建議啟動 50%、首版 30%、驗收 20%。'},
];
export default function ServiceShop({onChoose}:{onChoose?:(key:ServiceKey,summary:string)=>void}) {
 const [selected,setSelected]=useState(0);const offer=offers[selected];
 function select(index:number){setSelected(index);requestAnimationFrame(()=>document.getElementById('offer-detail')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'}));}
 return <section className="lk-shop lk-container" id="services" aria-labelledby="shop-title">
 <div className="lk-eyebrow">01 / 選一個目標，馬上看方案</div><div className="lk-shop-heading"><h2 id="shop-title">老闆，你想先<br className="lk-shop-break"/><em>解決哪件事？</em></h2><p>點選服務，就能看收費、包含內容與交付方式。<br/>先從一件事開始，讓成果說話。</p></div>
 <div className="lk-offer-cards" role="group" aria-label="選擇服務方案">{offers.map((o,i)=><button key={o.key} className="lk-offer-card" aria-pressed={selected===i} aria-controls="offer-detail" onClick={()=>select(i)}><div className="lk-offer-image"><img src={`/heroes/${o.image}-900.webp`} alt={o.alt} width="900" height="600" loading="lazy"/><span>{i===0?'月度合作':'單次專案'}</span></div><div className="lk-offer-copy"><small>{o.need}</small><h3>{o.title}</h3><p>{o.summary}</p><strong className={o.key === 'content' ? 'lk-price-range' : undefined}><span>NT$ </span>{o.price}<small>{o.unit}</small></strong><div>看內容與收費 <ChevronDown size={17}/></div></div></button>)}</div>
 <p className="lk-shop-note">方案參考價，皆為新臺幣未稅；實際範圍與排程依正式報價確認。圖片為 AI 生成情境示意。</p>
 <div className="lk-offer-detail" id="offer-detail" aria-live="polite" aria-atomic="true"><div className="lk-offer-intro"><span className="lk-eyebrow">你選擇的方案</span><h3>{offer.title}</h3><p>{offer.summary}</p><strong className={offer.key === 'content' ? 'lk-price-range' : undefined}>NT$ {offer.price}<small>{offer.unit}</small></strong><span className="lk-reference-price">方案參考價 · 未稅</span>{onChoose && <button className="lk-button lk-button-primary" onClick={()=>onChoose(offer.key,`想了解${offer.title}，參考價 NT$${offer.price}${offer.unit}（未稅）。希望確認交付範圍與可排交期。`)}>我想了解這個方案 <ArrowUpRight size={18}/></button>}<a className="lk-text-link" href="#comparison">跟請一位小編有什麼不同？ <ArrowUpRight size={16}/></a></div><div className="lk-offer-scope"><h4>{offer.key === 'content' ? '35,000 元基本月包包含' : '你會拿到什麼'}</h4>{offer.key === 'content' && <p className="lk-range-explainer">月費 NT$35,000–50,000，依內容數量、影音規格與協作工作量報價。以下為基本組合；擴充項目與數量先列入提案確認。</p>}<ul>{offer.items.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><div className="lk-offer-facts"><div><h4><Clock3 size={16}/>交付節奏</h4><p>{offer.time}</p></div><div><h4>修改與確認</h4><p>{offer.revision}</p></div><div><h4>你要準備</h4><p>{offer.input}</p></div><div><h4>付款方式建議</h4><p>{offer.payment}</p></div></div><details><summary>哪些費用與工作不包含？</summary><p>{offer.extra}</p></details><small>AI 協助製作，專人檢查品牌、資訊與交付品質；交期自素材、權限與需求確認後起算，不含等候回覆與需求變更時間。</small></div></div>
 {onChoose && <div className="lk-shop-more"><span>想做 AI 商業模式、客服或代理合作？</span><button className="lk-text-link" onClick={()=>onChoose('business','想討論 AI 商業模式、客服或代理合作的客製服務與報價。')}>聊聊客製需求 <ArrowUpRight size={16}/></button></div>}
 </section>
}
export function TeamComparison(){const rows=[['買到什麼','一位專職夥伴的時間與能力','約定的企劃、圖文、影音交付成果'],['技能範圍','依人選專長；跨領域可另找夥伴','同一窗口整合企劃、設計與剪輯'],['工作節奏','可即時安排日常任務與臨時回應','確認方向後，AI 批次產出、專人檢查'],['老闆怎麼管理','日常帶人、排工作與確認成果','定目標、給素材、集中審稿'],['現場與互動','適合現場拍攝、社群互動與內部協作','遠端交付；到場拍攝、即時客服另估'],['軟體與自動化','依個人能力，可能需另外委外','可接續購買流程／軟體專案，另計費']];return <section className="lk-comparison" id="comparison"><div className="lk-container"><div className="lk-eyebrow">小編、設計、剪輯、廣告、工程，一個窗口</div><h2>一個人的成本，<br/><em>五個人的產能。</em></h2><div className="lk-compare-head"><div><span>聘請一位小編</span><strong>1 位專職夥伴</strong><p>薪資由你與人選約定<br/>另考量雇主負擔、設備與管理成本</p></div><div><span>LUXKEY 五倍行銷月包</span><strong className="lk-comparison-price"><span>NT$35,000</span><span>–50,000</span><small>／月未稅</small></strong><p>35,000 元起：8 則圖文＋4 支短影音<br/>月度企劃，依工作量擴充報價</p></div></div><div className="lk-compare-table" role="table" aria-label="正職小編與 LUXKEY 五倍行銷月包比較"><div role="row" className="lk-compare-labels"><span role="columnheader">比較項目</span><span role="columnheader">正職小編</span><span role="columnheader">LUXKEY AI 團隊</span></div>{rows.map(([label,left,right])=><div role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{left}</span><span role="cell"><Check size={16}/>{right}</span></div>)}</div><p className="lk-shop-note">「五倍」是整合多種專長的品牌定位，實際產能依約定範圍；比較的是合作模式，非所有小編的能力上限。正職更適合長期駐點、即時互動；AI 團隊適合明確目標、批次製作。月包不包含軟體、自動化建置及廣告費，亦不代表與任何職位的完整聘僱成本相等。</p><a className="lk-button lk-button-primary" href="#services">看看哪個方案適合我 <ArrowUpRight size={18}/></a></div></section>}
